### ISSUE TITLE
Update migration topics to match R10 best practice

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1836]
**Scope** (articles to review and update):
| Title | File | Associated PR
| :-- | :-- | :--
| Migration overview | articles/v4sdk/migration/migration-overview.md | TBD
| Differences between the v3 and v4 .NET SDK | articles/v4sdk/migration/migration-about.md | TBD
| Differences between the v3 and v4 JavaScript SDK | articles/v4sdk/migration/migration-about-javascript.md | TBD
| Converting to a skill overview | articles/v4sdk/migration/convert-to-skill-overview.md | up to date
| .NET migration quick reference | articles/v4sdk/migration/net-migration-quickreference.md | TBD
| JavaScript migration quick reference | articles/v4sdk/migration/javascript-migration-quickreference.md | TBD
| Migrate a .NET v3 bot to a .NET Framework v4 bot | articles/v4sdk/migration/conversion-framework.md | TBD
| Migrate a .NET v3 bot to a .NET Core v4 bot | articles/v4sdk/migration/conversion-core.md | TBD
| Using .NET v3 user state in a v4 bot | articles/v4sdk/migration/csharp-user-state-using.md | TBD
| Migrate a JavaScript v3 bot to a v4 bot | articles/v4sdk/migration/conversion-javascript.md | TBD
| Using JavaScript v3 user state in a v4 bot | articles/v4sdk/migration/javascript-user-state-using.md | TBD
| Convert a .NET v3 bot to a skill | articles/v4sdk/migration/net-v3-as-skill.md | Update manifest version number, ask Eric and Gabo for a sanity check.
| Convert a JavaScript v3 bot to a skill | articles/v4sdk/migration/javascript-v3-as-skill.md | Update manifest version number, ask Eric and Gabo for a sanity check.

Also content about adaptive dialogs and Composer, along with a few hints. (Can use Eric as resource but not a writer.)
- hit concepts that are present in v3 that weren't handled well in v4 before adaptive (how adaptive serves you better):
  - interruptions,...?

In general, nudge them towards adaptive everywhere, especially for new bot work (skill consumers, etc.).

Verify that our statements about the following are still correct, and discuss newer features as relevant:
- [ ] skills
- [ ] dialog control: in general
- [ ] interruption handling via adaptive dialogs
- [ ] bot and dialog state with respect to NoTypeHandling serialization

**Time frame**  
Shortly after the R10 release

**Dev resources**
- Eric Dahlvang C#
- Michael Richardson JS
- Vishwac: adaptive
- Gabo: skills
- If we need a Composer resource, check with Chirstopher W
- Eyal (PM)

**Comment by scheyal** [comment]
Yes, we need to update the docs. In particular we need to add (& recommend) adaptive & composer entries, and ensure skills are uptodate. In particular adaptive solves a few flows that may be better mapped to how V3 interruption dialog handling.

Plus:
* General V3V4: @EricDahlvang 
* Adaptive: @vishwacsena 
* Composer: Chris W.

**Comment by EricDahlvang** [comment]
The dotnet UserState doc and samples are out dated.  The v4 sdk BotState classes now supports NoTypeHandling serialization, so user state storage should be easily transferable from a v3 to v4 bot.  (note: the dialogs library in v4 does not yet support no type handling, but the BotState classes do)

**Comment by JonathanFingold** [comment]
from Eyal
> Michael M. and Jonathan may reach out to you to help with specific items. We plan this work for post R10.
> 
> I proposed the following approach:
> - Add pointers, brief paragraph to nudge in appropriate areas a move towards adaptive, composer as applicable. Particularly since in some cases adaptive interruption model matches better V3 practices.
> - In principle, the current migration guidance is still relevant and appropriate.
> - Do not write new samples or modify old ones (unless incorrect). Augment by referring to existing adaptive / composer samples/content for new approach.
> - Review skills as there’s been some work there recently and we need to ensure it is accurate
> - Resources:
>   - Docs: Michael M & Jonathan
>   - Dev support: Eric Dahlvang [primary], Vishwac Sena Kannan [adaptive], Michael Richardson (TEKsystems) [Javascript]
>   - Backup: Eyal
> - Timeline: post R10, tracked by doc team.
> - Issue: Update migration topics to match R10 best practice #1836.
