### ISSUE TITLE
Create checklist for PR review process

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#1976]
Make a checklist to follow and tasks to complete when reviewing PRs:

### High-level stuff

- [ ] Install useful extensions. re: [Install content authoring tools](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-tools?branch=master)
- [ ] There are some known topic types with specific guidance. Note that this guidance is under active development and changes unpredictably. re: [overview](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-overview?branch=master), [quickstart](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-mvc-quickstart?branch=master), [tutorial](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-mvc-tutorial?branch=master). [FAQ](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-faq-guide), and others also listed in the **Topic types** section.
- [ ] Avoid adding certain types of content. re: [What (not to) publish](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-channel-guidance?branch=master), [Where to host downloadable files](https://review.docs.microsoft.com/en-us/help/contribute/downloadable-files?branch=master).

### More specific guidance

- [ ] Titles, metadata, and SEO. re: [SEO basics](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-seo-basics?branch=master) and  the rest of the articles in this section.
- [ ] File names: all lower case, balance of short versus descriptive, don't repeat parent directory names in file names. re: [How to name graphics files](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-create-screenshot?branch=master#how-to-name-graphics-files).
- [ ] Tabbed content
- Image guidance 
  - [ ] Alt text
  - [ ] Image types and markdown
- [ ] Avoid curly quotes. re: [include code in docs](https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master) (public: [code in docs](https://docs.microsoft.com/en-us/contribute/code-in-docs)), [quotation marks](https://docs.microsoft.com/en-us/style-guide/punctuation/quotation-marks)
- [ ] Use the right **kind of link**: in-repo, site-relative, or full URL, with appropriate **link text**. re: [links](https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master) (public: [links](https://docs.microsoft.com/en-us/contribute/how-to-write-links)).
- Code snippet guidance
  - [ ] Alt text: descriptive, unique.
  - [ ] Skipping lines: when an how to, when not to, considerations.
  - [ ] Highlighting lines: when an how to, when not to, considerations.
- [ ] Heading text. No duplicate headings. No H2s in tabbed content. (Consider team-specific rules of thumb for headings.)
- [ ] Capitalization issues and product names.
- [ ] Tone, voice, and word choice.
- [ ] Typography
